version: '3'
services:
  db:
    image: mariadb:10
    container_name: cypht-db
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=cypht
      - MYSQL_USER=cypht
      - MYSQL_PASSWORD=cyhpht_pass
  cypht:
    image: cypht:alpine
    container_name: cypht
    volumes:
      - ./hm3/users=CYPHT_USER_SETTINGS_DIR=/var/lib/hm3/users
      - ./hm3/attachments=CYPHT_ATTACHMENT_DIR=/var/lib/hm3/attachments
      - ./hm3/app_data=CYPHT_APP_DATA_DIR=/var/lib/hm3/app_data
    ports:
      - "8080:80"
    environment:
      #- CYPHT_SESSION_TYPE=PHP
      #- CYPHT_AUTH_TYPE=DB
      #- CYPHT_AUTH_USERNAME=your_username
      #- CYPHT_AUTH_PASSWORD=your_password
      #- CYPHT_LDAP_AUTH_SERVER=localhost
      #- CYPHT_LDAP_AUTH_PORT=389
      #- CYPHT_LDAP_AUTH_TLS=
      #- CYPHT_LDAP_AUTH_BASE_DN="example,dc=com"
      #- CYPHT_IMAP_AUTH_NAME=localhost
      #- CYPHT_IMAP_AUTH_SERVER=localhost
      #- CYPHT_IMAP_AUTH_PORT=143
      #- CYPHT_IMAP_AUTH_TLS=
      #- CYPHT_POP3_AUTH_NAME=localhost
      #- CYPHT_POP3_AUTH_SERVER=localhost
      #- CYPHT_POP3_AUTH_PORT=110
      #- CYPHT_POP3_AUTH_TLS=
      #- CYPHT_DEFAULT_SMTP_NAME=
      #- CYPHT_DEFAULT_SMTP_SERVER=
      #- CYPHT_DEFAULT_SMTP_PORT=
      #- CYPHT_DEFAULT_SMTP_TLS=
      #- CYPHT_DEFAULT_SMTP_NO_AUTH=
      #- CYPHT_USER_CONFIG_TYPE=file
      #- CYPHT_USER_SETTINGS_DIR=/var/lib/hm3/users
      #- CYPHT_ATTACHMENT_DIR=/var/lib/hm3/attachments
      #- CYPHT_APP_DATA_DIR=/var/lib/hm3/app_data
      #- CYPHT_DISABLE_TLS=false
      #- CYPHT_DISABLE_ORIGIN_CHECK=false
      #- CYPHT_ADMIN_USERS=
      #- CYPHT_COOKIE_DOMAIN=
      #- CYPHT_DEFAULT_EMAIL_DOMAIN=
      #- CYPHT_REDIRECT_AFTER_LOGIN=
      #- CYPHT_APP_NAME=Cypht
      #- CYPHT_DEFAULT_LANGUAGE=en
      #- CYPHT_JS_COMPRESS=false
      #- CYPHT_CSS_COMPRESS=false
      #- CYPHT_ENABLE_MEMCACHED=true
      #- CYPHT_MEMCACHED_SERVER=127.0.0.1
      #- CYPHT_MEMCACHED_PORT=11211
      #- CYPHT_ENCRYPT_AJAX_REQUESTS=
      #- CYPHT_ENCRYPT_LOCAL_STORAGE=
      #- CYPHT_DB_CONNECTION_TYPE=host
      #- CYPHT_DB_HOST=127.0.0.1
      #- CYPHT_DB_SOCKET=/var/lib/mysqld/mysqld.sock
      #- CYPHT_DB_NAME=test
      #- CYPHT_DB_USER=test
      #- CYPHT_DB_PASS=123456
      #- CYPHT_DB_DRIVER=mysql
      #- CYPHT_MODULE_CORE=enable
      #- CYPHT_MODULE_CONTACTS=enable
      #- CYPHT_MODULE_LOCAL_CONTACTS=enable
      #- CYPHT_MODULE_LDAP_CONTACTS=disable
      #- CYPHT_MODULE_GMAIL_CONTACTS=disable
      #- CYPHT_MODULE_FEEDS=enable
      #- CYPHT_MODULE_POP3=enable
      #- CYPHT_MODULE_IMAP=enable
      #- CYPHT_MODULE_2FA=disable
      #- CYPHT_MODULE_SMTP=enable
      #- CYPHT_MODULE_ACCOUNT=enable
      #- CYPHT_MODULE_IDLE_TIMER=enable
      #- CYPHT_MODULE_CALENDAR=enable
      #- CYPHT_MODULE_THEMES=enable
      #- CYPHT_MODULE_NUX=enable
      #- CYPHT_MODULE_DEVELOPER=enable
      #- CYPHT_MODULE_GITHUB=disable
      #- CYPHT_MODULE_RECAPTCHA=disable
      #- CYPHT_MODULE_WORDPRESS=disable
      #- CYPHT_MODULE_HISTORY=enable
      #- CYPHT_MODULE_SAVED_SEARCHES=enable
      #- CYPHT_MODULE_NASA=disable
      #- CYPHT_MODULE_PROFILES=enable
      #- CYPHT_MODULE_INLINE_MESSAGE=enable
      #- CYPHT_MODULE_IMAP_FOLDERS=enable
      #- CYPHT_MODULE_KEYBOARD_SHORTCUTS=enable
      #- CYPHT_MODULE_SITE=disable
      #- CYPHT_MODULE_DYNAMIC_LOGIN=disable
      #- CYPHT_MODULE_API_LOGIN=disable
      #- CYPHT_API_LOGIN_KEY=
      #- CYPHT_MODULE_RECOVER_SETTINGS=disable
      #- CYPHT_MODULE_HELLO_WORLD=disable
